# Generated by Django 4.2.5 on 2023-10-17 15:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("blog", "0006_blogpost_views"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="love",
            field=models.ManyToManyField(
                blank=True, related_name="love_posts", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
