# Generated by Django 4.2.5 on 2023-10-17 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0007_blogpost_love"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blogpost",
            name="love",
        ),
        migrations.AddField(
            model_name="blogpost",
            name="love",
            field=models.IntegerField(default=0),
        ),
    ]
