# Generated by Django 4.2.5 on 2023-10-17 15:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("blog", "0008_remove_blogpost_love_blogpost_love"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blogpost",
            name="love",
        ),
        migrations.AddField(
            model_name="blogpost",
            name="love",
            field=models.ManyToManyField(
                blank=True, related_name="loved_posts", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
